name: Deploy React Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH

      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEY }}

    - name: Deploy to DigitalOcean
      run: |
        ssh -o StrictHostKeyChecking=no youruser@your_droplet_ip << 'EOF'
          cd /var/www/YOUR_REPO
          git pull origin main
          npm install
          npm run build
          sudo systemctl reload nginx

        EOF