name: Build, Push and Deploy

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/react-portfolio:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
          
            if ! command -v docker &> /dev/null
            then
                echo "Docker not found, installing Docker..."
                apt update
                apt install -y ca-certificates curl gnupg lsb-release
                mkdir -p /etc/apt/keyrings
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
                apt update
                apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
                systemctl enable docker
                systemctl start docker
                echo "Docker installed successfully"
            else
                echo "Docker is already installed"
            fi
            cd /var/www/ReactPortfolio
            git pull origin main
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-portfolio:latest
            docker stop react-portfolio || true
            docker rm react-portfolio || true
            docker rm -f $(docker ps -aq)
            docker run -d --name react-portfolio -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/react-portfolio:latest
            docker-compose -f docker-compose.monitoring.yml up -d